# Generated by Django 4.1 on 2022-08-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro_alter_marca_options_alter_marca_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Marcas',
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name_plural': 'Marca'},
        ),
    ]
